project_id = "mcvgtsoheayabjpdplcr"

[functions.create-drive-folder]
verify_jwt = true

[functions.drive-auth-callback]
verify_jwt = false

[functions.drive-auth-url]
verify_jwt = true

[functions.drive-test-connection]
verify_jwt = true

[functions.create-project-with-seq]
verify_jwt = true

[functions.system-operations]
verify_jwt = true
